In [1]:
from numerical_matrix_encoding import M_sorted_encoding, T_sorted_encoding, Spre_count_encoding

c:\Users\ardit\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\ardit\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
c:\Users\ardit\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
M_sorted_encoding([[8, 3], [5, 2], [1, 7]])

array([1, 2, 3, 5, 7, 8])

In [3]:
T_sorted_encoding([[8, 3], [5, 2], [1, 7]])

array([[1, 5, 8],
       [2, 3, 7]])

In [4]:
Spre_count_encoding([8, 3, 5, 2, 1, 7], vector_length=10)

array([6., 5., 4., 3., 3., 2., 2., 1., 0., 0.])